plugins { id 'org.springframework.boot' }

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-restclient'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
}

bootJar { archiveFileName = 'example-web.jar' }
