[versions]
spring-boot = "4.0.1"
spring-dependency-management = "1.1.7"
spring-cloud = "2025.1.0"
spring-cloud-contract = "5.0.0"
commons-validator = "1.10.1"
uuid-generator = "5.2.0"
hypersistence-tsid = "2.1.4"
rest-assured = "6.0.0"
assertj = "3.27.6"
archunit = "1.4.1"

[libraries]
commons-validator = { module = "commons-validator:commons-validator", version.ref = "commons-validator" }
uuid-generator = { module = "com.fasterxml.uuid:java-uuid-generator", version.ref = "uuid-generator" }
hypersistence-tsid = { module = "io.hypersistence:hypersistence-tsid", version.ref = "hypersistence-tsid" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "rest-assured" }
rest-assured-spring-mock-mvc = { module = "io.rest-assured:spring-mock-mvc", version.ref = "rest-assured" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
archunit = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spring-cloud-contract = { id = "org.springframework.cloud.contract", version.ref = "spring-cloud-contract" }
