version: '3.8'

services:
  admin-angular:
    image: algashop/algashop-admin:dev
    build:
      context: .
      dockerfile: development.Dockerfile
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
