algashop:
  api-url: http://api.algashop.local:9999
  auth-with-alga-security-path: /oauth2/authorization/algashop-ecommerce-web
  payment-provider-public-key: tDBmh0ZiDrmaZ8BVQD7i9UYdcj9KtZUk
  payment-provider-credit-card-token-url: http://fastpay:9995/api/v1/public/tokenized-cards
  authorization-server-url: http://auth.algashop.local:8081

spring:
  data:
    redis:
      host: algashop-redis
      port: 6379
      password: redis123
      database: 4
  security:
    oauth2:
      client:
        registration:
          algashop-ecommerce-web:
            provider: algashop-auth
            client-id: algashop-ecommerce-web
            client-secret: ${ALGASHOP_ECOMMERCE_WEB_CLIENT_SECRET:ecommerce123}
            redirect-uri: http://algashop.local:9080/login/oauth2/code/algashop-ecommerce-web
            authorization-grant-type: authorization_code
            scope:
              - "openid"
              - "orders:read"
              - "orders:write"
              - "customers:read"
              - "customers:write"
              - "shopping-carts:read"
              - "shopping-carts:write"
              - "credit-cards:read"
              - "credit-cards:write"
              - "invoices:read"
            client-name: algashop-ecommerce-web
          backend:
            provider: algashop-auth
            client-id: algashop-ecommerce-m2m
            client-secret: ${ALGASHOP_ECOMMERCE_M2M_CLIENT_SECRET:m2m123}
            authorization-grant-type: client_credentials
            scope:
              - "products:read"
              - "categories:read"
              - "users:write"
              - "shipping-costs:preview"
            client-name: algashop-ecommerce-m2m
        provider:
          algashop-auth:
            issuer-uri: ${algashop.authorization-server-url}