spring:
  datasource:
    url: jdbc:postgresql://ho-postgres:5432/exampleapi
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/testdata
    url: jdbc:postgresql://ho-postgres:5432/exampleapi

